#!/bin/bash

# Check if all four parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Display information
echo "Transferring file $FILE_PATH to $USERNAME@$SERVER_IP:~/"

# Use scp to transfer the file with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "Error: File transfer failed."
fi

